#!/bin/bash
#
# imgurdrop
#
# Watches a folder (/tmp/imgur) for new files and uploads any new files
# in folder to imgur.  The imgur URL will then appear in your clipboard.
# 
# Intended to be used as a daemon, via dtach, screen, or simply "imgurdrop &"
#
# Originally inspired by:
# http://sirupsen.com/a-simple-imgur-bash-screenshot-utility/
#
# Dependencies:
#
# Xclip
# Comment: Xclip is what makes the script able to inject the direct url
# into your clipboard.
#
# libnotify*
# Comment: Will notify you whenever the direct URL is in the clipboard
#
# inotify-tools
# Comment: allows monitoring of the imgur drop directory
#

function uploadImage {
  curl -s -F "image=@$1" -F "key=486690f872c678126a2c09a9e196ce1b" http://imgur.com/api/upload.xml | grep -E -o "<original_image>(.)*</original_image>" | grep -E -o "http://i.imgur.com/[^<]*"
}

mkdir /tmp/imgur 2>/dev/null

while true; do
    file=`inotifywait -q -e create --format '%f' /tmp/imgur`
    uploadImage /tmp/imgur/$file | xclip -selection c
    notify-send "$file uploaded to imgur"
done
